Modulo5/IsaakNewtonWeb/Models/ErrorViewModel.cs
namespace IsaakNewtonWeb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Modulo5/IsaakNewtonWeb/Controllers/AgendamentoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using IsackNewton.Data;
using IsacNewton.Service.AgendamentoService.Implements;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IsaakNewtonWeb.Controllers
{
    public class AgendamentoController : Controller
    {
        private readonly ILogger<AgendamentoController> _logger;

        public AgendamentoController(ILogger<AgendamentoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Agendamento model)
        {
            CrudAgendamento crudAgendamento = new CrudAgendamento();

            crudAgendamento.Create(model);

            List<Agendamento> agendamentos = crudAgendamento.Read();
            Agendamento agendamentoCadastrado = agendamentos.Find(x => x.Id == model.Id);

            if (agendamentoCadastrado != null)
            {
                Console.WriteLine("Agendamento cadastrado:");
                Console.WriteLine(agendamentoCadastrado.DataAgendamento);
            }

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Modulo5/IsaakNewtonWeb/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IsaakNewtonWeb.Controllers
{
    [Route("[controller]")]
    public class FuncionarioController : Controller
    {
        private readonly ILogger<FuncionarioController> _logger;

        public FuncionarioController(ILogger<FuncionarioController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Modulo5/IsaakNewtonWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IsaakNewtonWeb.Models;

namespace IsaakNewtonWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Modulo5/IsaakNewtonWeb/Controllers/MedicoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IsaakNewtonWeb.Controllers
{
    [Route("[controller]")]
    public class MedicoController : Controller
    {
        private readonly ILogger<MedicoController> _logger;

        public MedicoController(ILogger<MedicoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Modulo5/IsaakNewtonWeb/Controllers/PacienteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IsaakNewtonWeb.Controllers
{
    [Route("[controller]")]
    public class PacienteController : Controller
    {
        private readonly ILogger<PacienteController> _logger;

        public PacienteController(ILogger<PacienteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Modulo5/IsaakNewtonWeb/Controllers/SalaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IsaakNewtonWeb.Controllers
{
    [Route("[controller]")]
    public class SalaController : Controller
    {
        private readonly ILogger<SalaController> _logger;

        public SalaController(ILogger<SalaController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Modulo5/IsaakNewtonWeb/Views/Agendamento/Create.cshtml
@model IsackNewton.Data.Agendamento

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastrar Agendamento</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataAgendamento" class="control-label">Data</label>
                <input asp-for="DataAgendamento" class="form-control" />
                <span asp-validation-for="DataAgendamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Procedimento" class="control-label"></label>
                <input asp-for="Procedimento" class="form-control" />
                <span asp-validation-for="Procedimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Modulo5/IsaakNewtonWeb/Views/Agendamento/Index.cshtml
<div>
    <h2>Agendamentos</h2>

    <ul>
        <li>
            <a asp-controller="Agendamento" asp-action="Create">
                Cadastrar
            </a>
        </li>
        <li>
            <a asp-controller="Agendamento" asp-action="Update">
                Editar
            </a>
        </li>
        <li>
            <a asp-controller="Agendamento" asp-action="Delete">
                Excluir
            </a>
        </li>
    </ul>
</div>

Modulo5/IsaakNewtonWeb/Views/Funcionario/Create.cshtml
@model IsackNewton.Data.Funcionario

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastrar Funcionário</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SobreNome" class="control-label"></label>
                <input asp-for="SobreNome" class="form-control" />
                <span asp-validation-for="SobreNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cargo" class="control-label"></label>
                <input asp-for="Cargo" class="form-control" />
                <span asp-validation-for="Cargo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Turno" class="control-label"></label>
                <input asp-for="Turno" class="form-control" />
                <span asp-validation-for="Turno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salario" class="control-label"></label>
                <input asp-for="Salario" class="form-control" />
                <span asp-validation-for="Salario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group my-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Modulo5/IsaakNewtonWeb/Views/Funcionario/Index.cshtml
<div>
    <h2>Funcionários</h2>

    <ul>
        <li>
            <a asp-controller="Funcionario" asp-action="Create">
                Cadastrar
            </a>
        </li>
        <li>
            <a asp-controller="Funcionario" asp-action="Update">
                Editar
            </a>
        </li>
        <li>
            <a asp-controller="Funcionario" asp-action="Delete">
                Excluir
            </a>
        </li>
    </ul>
</div>

Modulo5/IsaakNewtonWeb/Views/Sala/Create.cshtml
<h1>Cadastrar Sala</h1>

Modulo5/IsaakNewtonWeb/Views/Sala/Index.cshtml
<div>
    <h2>Salas</h2>

    <ul>
        <li>
            <a asp-controller="Sala" asp-action="Create">
                Cadastrar
            </a>
        </li>
        <li>
            <a asp-controller="Sala" asp-action="Update">
                Editar
            </a>
        </li>
        <li>
            <a asp-controller="Sala" asp-action="Delete">
                Excluir
            </a>
        </li>
    </ul>
</div>

Modulo5/IsaakNewtonWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IsaakNewtonWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IsaakNewtonWeb.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IsaakNewtonWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Agendamento" asp-action="Index">Agendamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionários</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medico" asp-action="Index">Médicos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paciente" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sala" asp-action="Index">Salas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IsaakNewtonWeb
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>